name: JavaTest
version: '${project.version}'
main: me.isz.javatest.JavaTest
api-version: 1.18
authors: [ Isz ]
description: plugin for testing purposes
commands:
  god:
    description: Become invincible
    usage: /<command>
  feed:
    description: refill your hunger
    usage: /<command>
  sendword:
    description: send a word
    usage: /<command>
  kill:
    description: kills a player
    usage: /<command>
  fly:
    description: Enables fly
    usage: /<command>